apiVersion: v1
kind: Service
metadata:
  name: auth-server
spec:
  selector:
    app: auth-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: time-server
spec:
  selector:
    app: time-server
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: LoadBalancer